name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

  workflow_dispatch:

env:
  build_cache_name: hexo-public

jobs:
  build:
    name: Build static Hexo content
    runs-on: ubuntu-latest
    steps:

      - name: Checkout including submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_CHECKOUT_TOKEN }}
          submodules: true
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Hexo
        run: npm install && npm install hexo-cli -g
      
      - name: Hexo generate
        run: hexo generate

      - name: Cache Hexo build
        uses: actions/cache/save@v3
        with:
          path: ./public
          key: ${{ env.build_cache_name }}

  deploy:
    name: Deploy content to Azure
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Restore Hexo build
        uses: actions/cache/restore@v3
        with:
          path: ./public
          key: ${{ env.build_cache_name }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Clean storage
#        uses: azure/CLI@v1
#        with:
#          inlineScript: |
#            az storage blob delete-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key --source '$web'

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key --destination '$web' --source ./public --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --name ${{ secrets.AZURE_CDN_ENDPOINT_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait

      - name: Azure logout
        run: |
          az logout
        if: always()
